version: '3.4'

services:
  xwiki:
    image: r1co/docker-xwiki
    ports:
      - 8080:8080
    volumes:
      - xwiki-data:/usr/local/tomcat/webapps/ROOT/WEB-INF
      - xwiki-data:/var/local/xwiki

networks:
  default:
    external:
      name:  default_overlay

volumes:
  xwiki-data: